frist commit with implementation of test case to move cards to anohte…
mefemefe/robot_project pull request #27
Opened 2022-06-26 19:22 UTC by nicolasvallejo13

…r board

´´´
Verify A Card Can Be Created                                          | PASS |
------------------------------------------------------------------------------
Modify A Card's Name From The Board Page                              | PASS |
------------------------------------------------------------------------------
Leave A Comment On A Card                                             | PASS |
------------------------------------------------------------------------------
Verify A Card Can Be Deleted                                          | PASS |
------------------------------------------------------------------------------
Card Can Be Dragged To Another List                                   | PASS |
------------------------------------------------------------------------------
Card Can Be Moved To Another Board                                    ...[8804:15044:0624/171656.288:ERROR:device_event_log_impl.cc(214)] [17:16:56.287] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Uno de los dispositivos conectados al sistema no funciona. (0x1F)
[8804:15044:0624/171656.296:ERROR:device_event_log_impl.cc(214)] [17:16:56.295] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Uno de los dispositivos conectados al sistema no funciona. (0x1F)
Card Can Be Moved To Another Board                                    | PASS |
------------------------------------------------------------------------------
Trello Gui Cards :: Test Cases for Cards Feature                      | PASS |
6 tests, 6 passed, 0 failed
´´´

2022-06-27 20:07 UTC, mefemefe commented on tests/trello/gui/resources/components/TrelloUpperMenu.resource
> +${TRELO_ICON}             xpath://a[@aria-label='Back to home']
```suggestion
${TRELLO_ICON}             xpath://a[@aria-label='Back to home']
```

2022-06-27 20:07 UTC, mefemefe commented on tests/trello/gui/resources/components/TrelloUpperMenu.resource
> +     Click Element           ${TRELO_ICON}
```suggestion
     Click Element           ${TRELLO_ICON}
```

2022-06-27 20:08 UTC, mefemefe commented on tests/trello/gui/resources/components/CardModal.resource
> +    Click Element    ${ACEPT_MOVE_BUTTON}
```suggestion
    Click Element    ${ACCEPT_MOVE_BUTTON}
```

2022-06-28 11:37 UTC, mefemefe commented on tests/trello/gui/trello_gui_cards.robot
> +    Wait Until Keyword Succeeds    10    2.5    Delete A Board            ${board2.json()}[id]
The process of deleting the board should be a teardown

2022-06-28 11:38 UTC, mefemefe requested changes

2022-06-28 11:38 UTC, mefemefe commented on tests/trello/gui/trello_gui_cards.robot
> +    Wait Until Keyword Succeeds    10    2.5    Delete A Board            ${board2.json()}[id]
The process of deleting the board should be a teardown

2022-06-28 20:26 UTC, sebasonti-fundjala approved these changes

2022-06-28 20:33 UTC, mefemefe requested changes

2022-06-28 20:33 UTC, mefemefe commented on tests/trello/gui/trello_gui_cards.robot
> +erify A Card Can Be Created
```suggestion
Verify A Card Can Be Created
```

2022-06-29 17:12 UTC, mefemefe approved these changes

2022-06-29 17:14 UTC, nicolasvallejo13 commented
.

2022-06-29 17:14 UTC, nicolasvallejo13 commented
solved lint problems and working all tests

2022-06-29 17:16 UTC, nicolasvallejo13 commented
test case to move cards to anohter board

2022-06-29 17:17 UTC, nicolasvallejo13 commented
test case to move cards to anohter board working and solved lint problems

2022-06-29 17:17 UTC, merged